POST http://localhost:8000
Content-Type: application/json

{
  "text": "--🗑️Aaaa",
  "features": "remove_emoji"
}

###
POST http://localhost:8000
Content-Type: application/json

{
        "text": "После взрыва на археологических раскопках в Месопотамии мир претерпел невообразимые изменения. Небо стало зеркальным, электроника таинственным образом вышла из строя, а дети, рождённые после того чудовищного происшествия, получали странные, паранормальные способности. От «общества» осталось одно название, а в самой гуще событий, приведших к катастрофе, оказалась группа юных мутантов, которые пытаются возродить мир под руководством женщины, называющей себя «Графиня [伯爵夫人]».\nГлавными героями истории становятся дети учёного [character=10898 тэрумити-мадока]Мадоки, Тацуя [円 竜也] и Киёко [円 紀世子].",
        "features": "remove_bbcode,remove_custom_bbcodes,remove_urls"
    }